"""Poster dan link pendaftaran event

Revision ID: c83c656ac7ec
Revises: 6ce170b1d50f
Create Date: 2024-11-26 21:19:20.987977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83c656ac7ec'
down_revision = '6ce170b1d50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('registration_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('registration_url')
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
